pipeline {
    agent any
    
    
    stages {
        stage('Build Docker Image') {
            steps {
                dir('/var/lib/jenkins/workspace/DevOpsDockerTask/ProductAPI') {
                    script {
                        sh 'docker build -t dockerassignment .'
                    }
                }
            }
        }
        stage('Login to Docker Registry') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'DockerHub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh 'docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}'
                    }
                }
            }
        }
        stage('Tag Docker Image') {
            steps {
                script {
                    sh 'docker tag dockerassignment:latest aditya050102/devops_assignmentt:dockerassignment'
                }
            }
        }
        stage('Push Docker Image to Registry') {
            steps {
                script {
                    sh 'docker push aditya050102/devops_assignmentt:dockerassignment'
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    sh 'docker run -d -p 8080:80 aditya050102/devops_assignmentt:dockerassignment'
                }
            }
        }

    }
}




































// pipeline {
//     agent any
    
    
//     stages {
//         stage('Build Docker Image') {
//             steps {
//                 dir('/var/lib/jenkins/workspace/DevOpsDockerTask/ProductAPI') {
//                     script {
//                         sh 'docker build -t dockerassignment .'
//                     }
//                 }
//             }
//         }
//         stage('Login to Docker Registry') {
//             steps {
//                 script {
//                     withCredentials([usernamePassword(credentialsId: 'DockerHub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
//                         sh 'docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}'
//                     }
//                 }
//             }
//         }
//         stage('Tag Docker Image') {
//             steps {
//                 script {
//                     sh 'docker tag dockerassignment:latest aditya050102/devops_assignmentt:dockerassignment'
//                 }
//             }
//         }
//         stage('Push Docker Image to Registry') {
//             steps {
//                 script {
//                     sh 'docker push aditya050102/devops_assignmentt:dockerassignment'
//                 }
//             }
//         }
//     }
// }





































































































































// pipeline {
//     agent any
    
//     stages {
//         stage('Build Docker Image') {
//             steps {
//                 dir('/var/lib/jenkins/workspace/DevOpsDockerTask/ProductAPI') {
//                     script {
//                         sh 'docker build -t dockerassignment .'
//                     }
//                 }
//             }
//         }
//         stage('Login to Docker Registry') {
//             steps {
//                 script {
//                     sh 'echo "Aditya@050102" | docker login -u "" --password-stdin'
//                 }
//             }
//         }
//         stage('Tag Docker Image') {
//             steps {
//                 script {
//                     sh 'docker tag dockerassignment:latest aditya050102/devops_assignment:dockerassignment'
//                 }
//             }
//         }
//         stage('Push Docker Image to Registry') {
//             steps {
//                 script {
//                     sh 'docker push aditya050102/devops_assignment:dockerassignment'
//                 }
//             }
//         }
//     }
// }






















































































































